"""empty message

Revision ID: ce6e23b4a668
Revises: a2c3a0375f62
Create Date: 2023-09-02 00:29:55.015398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e23b4a668'
down_revision = 'a2c3a0375f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(length=30), nullable=True),
    sa.Column('rotation_period', sa.String(length=30), nullable=True),
    sa.Column('orbital_period', sa.String(length=30), nullable=True),
    sa.Column('gravity', sa.String(length=30), nullable=True),
    sa.Column('population', sa.String(length=30), nullable=True),
    sa.Column('climate', sa.String(length=30), nullable=True),
    sa.Column('terrain', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
