"""empty message

Revision ID: e427f57d47b2
Revises: 38a55f43ff13
Create Date: 2023-09-02 00:47:51.671642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e427f57d47b2'
down_revision = '38a55f43ff13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.String(length=30), nullable=True))
        batch_op.drop_column('lenght')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenght', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_column('length')

    # ### end Alembic commands ###
